/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application;
import java.applet.Applet;
import java.awt.*;
/*<applet code="MyApplet" width="200" height="100">
</applet>
*/
/**
 *
 * @author LENOVO
 */
public class MyApplet extends java.applet.Applet {
        Label l1,l2;
        TextField t1,t2;
        Button b1;
    /**
     * Initializes the applet MyApplet
     */
    public void init() {
        try {
            l1=new Label("First number");
            l2=new Label("second number");
            t1=new TextField();
            t2=new TextField();
            b1=new Button("add");
            add(l1);
            add(l2);
            add(t1);
            add(t2);
            add(b1);
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
